version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8080:8080"
    depends_on:
      - chroma
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    volumes:
      - ./app:/app/app
      - ./pdf:/app/pdf

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  chroma_data: