version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=http://ollama:11434
    command: sh -c "while ! nc -z ollama 11434; do sleep 1; done && uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"
    depends_on:
      - ollama

volumes:
  ollama_data: